### PR TITLE
Turn theme into Preference Pack  

### PR DESCRIPTION
**Pull request by Chrismettal**
See related issue: #2 

Refactors the repo into easily installable PreferencePack, supported by FreeCAD version 0.20 and up.
Allows easier installation without overwriting/merging the user.cfg manually. After installing the PreferencePack to your FreeCAD installation, theme can be applied with one click in settings.

Installation instructions were also updated accordingly. 

I will open up a PR to the [addon manager repo](https://github.com/FreeCAD/FreeCAD-addons), adding this PreferencePack there, so it can be installed from within FreeCAD, without manually downloading/installing anything. This is already referenced in the installation manual.

I have taken the liberty to create an SVG Icon showing representative colors for the addon manager, similar to existing PreferencePacks to help users to get a glance of themes when scrolling through the addon manager.

Additionaly, the "Fully constrained" color in the sketcher was still set to default, and has been set to the green defined in the Dracula palette.

### CODE REVIEW

**Comment by luzpaz** [comment]
Awesome work here. Thanks @Chrismettal !

**Comment by luzpaz** [comment]
testers, please report issues? We're waiting upstream for this PR to be merged

**Comment by luzpaz** [comment]
Bumping

**Comment by tim-clifford** [comment]
Great work @Chrismettal, thanks for the PR! Just one thing, can you leave the original instructions in `INSTALL.md` as well as the new ones? (perhaps under a subheading like "FreeCAD <0.20") Since it looks like not all distros have 0.20 yet.

**Comment by Chrismettal** [comment]
> [...] can you leave the original instructions in INSTALL.md as well as the new ones?

Good call, didn't think about that! 

> [...] feel free to add yourself to the "Team" section [...]

Gladly!

**Pull request merged**
