### PR TITLE
Menubarfixes

### LINKED ISSUE #19: Menu arrows do not have enough contrast
dark menu arrows

### LINKED ISSUE #21: Disabled menubar items are not differentatiated from enabled ones
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

Hovering over the options lower in the menu here (screencast is missing the cursor, sorry!) is practically the only way to tell they're disabled.

[Screencast from 02-12-2023 02:07:06 PM.webm](https://user-images.githubusercontent.com/650565/218334470-0ab469fa-f553-4337-9458-5546196957fc.webm)

### LINKED ISSUE #22: Menubar icons too close to left edge
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

image

### LINKED ISSUE #23: No indication that menubar items are actually checkboxes
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

As seen below, "Macro" is another checkbox option but it's impossible to tell without the context of the other items already having checkmarks.

Checkboxes no indicator

### PR DESCRIPTION
**Pull request by brandonbeaumia**
> If you're fixing a UI issue, make sure you take two screenshots. One that shows the actual bug and another that shows how you fixed it.

Fixes #19
Fixes #21
Fixes #22
Fixes #23

Before:
[Menubarfixes before.webm](https://user-images.githubusercontent.com/650565/221385885-5b222d11-3d18-41eb-b8e8-83a7d9c9b550.webm)

After:
[Menubarfixes after.webm](https://user-images.githubusercontent.com/650565/221385895-a2eb6f23-9df0-48ec-ad0b-9843b74142e1.webm)

### CODE REVIEW

**Comment by brandonbeaumia** [comment]
@zenorocha able to take a look at this repo's permissions to enable some merges? Mentioned in #18 but that PR has since been merged; wanted to bring it up again in case it slipped past your radar. Thanks!

**Comment by brandonbeaumia** [comment]
Well, instead of granting @Chrismettal permissions like I requested in a DM to Zeno, someone just ended up adding _me_ instead. I don't feel comfortable merging without someone else testing first, though. Wanna start working your way through these to give me the go-ahead for each PR?

**Comment by brandonbeaumia** [comment]
Oh, a message just came through: apparently there was a goof-up during the repo creation and you now have access too! Hooray!

**Comment by Chrismettal** [comment]
Thank you so much for your contributions! I am happy to see that we both got push access actually!

There is only one thing I see a problem with this PR, which is the added padding for the icons. This alone will make the "checked" icon background get misaligned with the icon, which you can actually see in your "after" video as well.
I have reverted that single commit from your PR for now as I was unable to figure out a quick way of leaving the padding without getting the background misaligned, as I feel the bit of padding isn't that noticable to begin with. 
If you figure out how to keep the background aligned I would like to see the padding merged as well though.

**Comment by brandonbeaumia** [comment]
Yes, me too! Very glad to polish up this theme with you, it's so nice to use. Makes FC feel way more modern, too.

Oh, and good catch on the active background; I actually had to rewatch the video twice to see it even _after_ you pointed it out! Hopefully I'll get some time this weekend to look into it.

**Pull request merged**
